# Resource Locations

bwa_reference:
  /home/joseph/Documents/genomic_resources/bwa/human_g1k_v37.fasta
reference:
  /home/joseph/Documents/genomic_resources/reference_genomes/human_g1k_v37.fasta
reference_index:
  /home/joseph/Documents/genomic_resources/reference_genomes/human_g1k_v37.fasta.fai
dbsnp_vcf:
  /home/joseph/Documents/genomic_resources/dbsnp/dbsnp_138.b37.vcf
indels_1k_vcf:
  /home/joseph/Documents/genomic_resources/1000g/1000G_phase1.indels.b37.vcf
gold_standard_indels:
  /home/joseph/Documents/genomic_resources/1000g/Mills_and_1000G_gold_standard.indels.b37.vcf
dbsnp_vcf_eval:
  /home/joseph/Documents/genomic_resources/dbsnp/dbsnp_138.b37.excluding_sites_after_129.vcf
gnomad_exomes:
  /home/joseph/Documents/genomic_resources/gnomad/gnomad.exomes.r2.0.1.sites.vcf.gz
gnomad_genomes:
  /home/joseph/Documents/genomic_resources/gnomad/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz
1000k_high_confidence_snps:
  /home/joseph/Documents/genomic_resources/1000g/1000G_phase1.snps.high_confidence.b37.vcf
capture_bed_file:
  /home/joseph/Documents/gatk_snakemake/configs/IlluminaTruSightOne/IlluminaTruSightOne_ROI_b37.bed 
fastq_screen_config:
  /home/joseph/Documents/gatk_snakemake/configs/IlluminaTruSightOne/fastq_screen.txt
reference_sequence_dict:
  /home/joseph/Documents/genomic_resources/reference_genomes/human_g1k_v37.dict
vep_cache_location:
  /home/joseph/Documents/genomic_resources/vep/
genomic_superdups_bed:
  /home/joseph/Documents/genomic_resources/genomicsuperdups/genomicSuperDups_b37.bed.gz
picard_temp_dir:
  /tmp/
fastqc_temp_dir:
  /tmp/
samtools_temp_dir:
  /tmp/
spliceai:
  /home/joseph/Documents/genomic_resources/spliceai/exome_spliceai_scores.vcf.gz
ccr_bed:
  /home/joseph/Documents/genomic_resources/ccr/ccrs.all.v2.20180420_37.bed.gz
coverage_calculator:
  /home/joseph/Documents/apps/CoverageCalculatorPy/CoverageCalculatorPy.py
germline_hotspots:
  /home/joseph/Documents/gatk_snakemake/configs/GermlineEnrichment_Hotspots.bed
refseq:
  /home/joseph/Documents/genomic_resources/genes/ref_GRCh37.p13_top_level_canonical_b37_sorted.gff3.gz
filter_config:
  /home/joseph/Documents/gatk_snakemake/configs/filter_config.yaml
local_panel_app_dump:
  /home/joseph/panelappdump.csv
germline_variant_filter:
  /home/joseph/Documents/apps/germline_variant_filter/germline_variant_filter.py

# Alternate pipeline execution

perform_bqsr:
  true

# Variant Filtering Options

# SNPS
snp_min_qual:
  30.0
snp_min_QD:
  2.0
snp_max_FS:
  60.0
snp_min_MQ:
  40.0
snp_min_MQRankSum:
  -12.5 
snp_min_ReadPosRankSum:
  -8.0

# Non SNPs
indel_min_qual:
  30.0
indel_min_QD:
  2.0
indel_max_FS:
  200.0
indel_max_SOR:
  10.0
indel_min_ReadPosRankSum:
  -20.0
indel_min_inbreeding_coeff:
  -0.8
min_genotype_depth:
  10.0

# Min Coverage Cut Off
minimum_coverage:
  20


# Threads to Use
variant_evaluation_threads:
  1
bwa_threads:
  1
fastp_threads:
  1
fastq_screen_threads:
  1
fastqc_threads:
  1
manta_threads:
  1
vep_threads:
  1

# Java Options
java_home:
  /home/joseph/miniconda3/envs/germline_enrichment_main/bin/java
gatk_hc_java_options:
  "-XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/tmp/ -Xmx16g"
gatk_bqsr_java_options:
  "-XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/tmp/ -Xmx4g"
gatk_analyse_covariates_java_options:
  "-XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/tmp/ -Xmx2g"
gatk_variants_java_options:
 "-XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/tmp/ -Xmx4g"
gatk_genomics_db_java_options:
  "-XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/tmp/ -Xmx12g"
picard_memory_options:
  "-XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Djava.io.tmpdir=/tmp/ -Xmx20g"

# Misc Settings
# Max records in picard MarkDuplicates
merge_duplicates_max_records:
  2000000
chromosomes:
  ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']
interval_padding_bqsr:
  100
interval_padding_haplotype_caller:
  100

# Run Level Information
centre:
  AWGL
